# Generated by Django 4.2.7 on 2024-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0004_alter_grouppost_image_alter_grouppost_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
