# Generated by Django 4.2.7 on 2024-03-01 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0006_remove_interest_group_group_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest_group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
