# Generated by Django 4.2.7 on 2024-03-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0007_interest_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='feed_interest.interest_group'),
        ),
    ]
