# Generated by Django 4.2.7 on 2024-03-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0008_alter_grouppost_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest_group',
            name='created_at',
        ),
        migrations.AddField(
            model_name='interest_group',
            name='group_posts',
            field=models.ManyToManyField(related_name='group_posts', to='feed_interest.grouppost'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_interest.interest_group'),
        ),
    ]
