# Generated by Django 4.2.7 on 2024-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0009_remove_interest_group_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='author',
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_posts/'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
