# Generated by Django 4.2.7 on 2024-03-01 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed_interest', '0010_remove_grouppost_author_alter_grouppost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/group_post_images'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Расскажите что сегодня было интересного'),
        ),
    ]
