# Generated by Django 4.2.7 on 2024-03-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0011_grouppost_author_alter_grouppost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest_group',
            name='group_posts',
        ),
    ]
