# Generated by Django 4.2.7 on 2024-03-01 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0012_remove_interest_group_group_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest_group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='feed_interest.interest_group'),
        ),
    ]
