# Generated by Django 4.2.7 on 2024-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_interest', '0013_interest_group_created_at_alter_grouppost_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest_group',
            name='group_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание группы'),
        ),
    ]
